apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: express-api
  replicas: 3

  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
        - name: nginx
          image: "nginx:alpine"

          resources:
            request:
              memory: "128Mi"
              cpu: "400m"
            limits:
              memory: "512Mi"
              cpu: "1200m"

          readinessProbe:
            httpGet:
              path: "/"
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessprobe: #chequea que el puerto 80 esté abierto
            tcpSocket:
              port: 80
            initalDealySeconds: 15
            periodSeconds: 20

          ports:
            - containerPort: 80
