name: Dolar prize updater

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install --production
      - name: Build project
        run: npx tsc
      - name: Run script
        run: node ./dist/cron-updater/index.js
