name: Manual DB update

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: '14.x'

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Download Chrome or Chromium
        run: |
          Invoke-WebRequest "https://dl.google.com/chrome/win/stable/GGRO/googlechrome_standalone_enterprise_94.0.4606.81.msi" -OutFile "chrome.msi"
          msiexec /i chrome.msi /qn /norestart
          
      - name: Add Chrome or Chromium to path
        run: |
          $chromePath = "${env:ProgramFiles(x86)}\Google\Chrome\Application"
          $env:Path += ";$chromePath"
          Write-Host "Chrome path: $chromePath"
          
      - name: Install npm dependencies
        run: npm install
        
      - name: Build project
        run: npx tsc
      
      - name: Run cron
        env:
          MONGO_DB_CONNECTION_STRING: ${{ secrets.MONGO_DB_CONNECTION_STRING }}
        run: node -r dotenv/config ./dist/cron-updater/index.js
